
GET https://ticketing.dev/api/users/currentuser
###

POST https://ticketing.dev/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "jp",
  "password": "xe"
}
###

POST https://ticketing.dev/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "jp@thedog.com",
  "password": "x556677"
}
###

GET https://ticketing.dev/dogfood
###

POST https://ticketing.dev/dogfood HTTP/1.1
Content-Content-Type: application/json

{}
###